// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect if we're in Node.js environment (SSR/prerendering)
const isNode = typeof window === 'undefined';

const clientOptions: any = {
  auth: {
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    persistSession: typeof localStorage !== 'undefined',
    autoRefreshToken: typeof localStorage !== 'undefined',
  },
  realtime: {
    params: {
      eventsPerSecond: isNode ? 0 : 10,
    },
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, clientOptions);