// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isNode = typeof window === 'undefined';

// Lazy load Supabase client only on the client side
let supabaseInstance: any = null;

const initializeSupabase = () => {
  if (supabaseInstance) return supabaseInstance;
  if (isNode) return null; // Don't initialize in Node.js/SSR

  try {
    const { createClient } = require('@supabase/supabase-js');
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (error) {
    console.error('Failed to initialize Supabase client:', error);
  }

  return supabaseInstance;
};

// Create a proxy that initializes on first use
export const supabase = new Proxy({} as any, {
  get: (target, prop) => {
    const client = initializeSupabase();
    if (!client) {
      console.warn('Supabase client not available in this environment');
      return undefined;
    }
    return client[prop];
  },
});